### PR TITLE
Update dark mode and change the primary button color scheme

### PR DESCRIPTION
**Pull request by Xalavar**
Added a few new things to dark mode. Also, personally, I don't think `small-items.css` should really be changing the color of the primary button, especially since it almost blends in with the background in dark mode.

### CODE REVIEW

**Comment by Thorvarium** [comment]
Hey, removing the black from the light mode and keeping the text white made it look weird.
Just keep it in black in the normal mode and overwrite it to the yellow-wish in the dark mode

**Comment by Xalavar** [comment]
Should work now. I had to remove some of the important flags for small-items since dark mode can't take precedence with them there.

**Comment by Thorvarium** [comment]
There is one small error on the RFY/AFA/AI tabs when using the dark theme:
image

**Comment by Thorvarium** [comment]
Looking good now, thanks

**Pull request merged**
